AppBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hash:
            type: string
            length: 255
        message:
            type: text
    lifecycleCallbacks: {  }
